### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by pikaboo** [agentsim/Symbolicator#1]
It would be nice if you wrote how to use this app

**Comment by udondan** [comment]
Place all the files in the same folder:
- The `.crash` file
- Your application
- The `.dSYM` from your `.xcarchive`

Start the Symbolicator. Then simply drag the `.crash` file onto the Symbolicator Dock icon, like mentioned in the readme. The app will only accept files dragged on it with the `.crash` extension!

Apple sent me crash reports with `.txt` extension. Took me a while to figure out I'll have to rename it to work. :)
